# project definitions
project: pier_users
audience: users
product: all
platform: all
version: all
output: web
destination: ./_site/pier_users
topnav_title: Pier Documentation
homepage_title: Pier Documentation
site_title: Pier Documentation
project_folder: pier
company_name: Arloesol
footer_image_location: ./common_images/company_logo.png
github_editme_path: arloesol/pierdoc/edit/review
disqus_shortname: dockerpier
google_analytics: UA-71740910-2
# variables


sidebar_tagline: Pier
sidebar_version: Version 1.0
theme_file: theme-blue.css

port: 4009

exclude:
  - _site
  - _drafts
  - configs/

# same for all
host: 0.0.0.0
feedback_email: pier@arloesol.com

highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true
